"""added email to user

Revision ID: df7726ad5027
Revises: 0558b3b29845
Create Date: 2020-03-13 22:25:04.457805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7726ad5027'
down_revision = '0558b3b29845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_role', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_role', 'user', ['role'], unique=False)
    # ### end Alembic commands ###
